### ISSUE TITLE
Image-toolkit does not work in live-preview mode

### ISSUE THREAD

**Issue by Superfeuchter** [sissilab/obsidian-image-toolkit#46]
I'm using Obsidian v0.14.5 now with live-preview mode instead of editor-mode.
When I hover over an image, the plus-symbol appears. 
And when I click on the image, the image dissappears instead of getting bigger.
Further, the toolbar does not open like it did in previous Obsidian versions.
It only works as usual in preview mode.

**Comment by sissilab** [comment]
> I'm using Obsidian v0.14.5 now with live-preview mode instead of editor-mode. When I hover over an image, the plus-symbol appears. And when I click on the image, the image dissappears instead of getting bigger. Further, the toolbar does not open like it did in previous Obsidian versions. It only works as usual in preview mode.

Please provide:
1. your theme's name
2. some enabled plugins about image
3. your markdown code about the image you clicked
4. screenshot or recording vidoes (if applicable)
Thanks for your feedback!

**Comment by Superfeuchter** [comment]
Thanks for your fast reply.
You asked good questions:

First I shot a video of the issue, then I deinstalled "Ozan's Image in editor" - plugin.
But nothing changed.
then I changed the theme from "golden Topaz" to the built-in standard-theme.
And suddenly it worked as it should, also in live-preview mode.

https://user-images.githubusercontent.com/83219956/162568097-28e16d69-7c19-4cbb-9a24-17c79dfd1382.mp4

So, I fear I have to use a different theme ...
Thanks for your help!

**Comment by sissilab** [comment]
@Superfeuchter 
Hi, 'Golden Topaz' is a greate theme. If you wanna keep it, you can modify its theme css file.
Editing `.obsidian\themes\Golden Topaz.css`, and you can commet the following code with `/* ... */` or delelte it directly.

```css
/* .view-content img:not([class="emoji"]):active {
  cursor: zoom-out;    
  position: fixed;
  object-fit: contain;
  height: 100%;
  width: 100%;
  padding: 0;
  top: 50%;  
  left: 0;
  right: 0;
  bottom: 0;
  transform: translateY(-50%);
  z-index: 200;
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgdmlld0JveD0iMCAwIDgwIDgwIj4KICA8ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgPHJlY3Qgd2lkdGg9IjgwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjRjJGNEY2Ii8+CiAgICA8ZyBmaWxsPSIjRkZGIj4KICAgICAgPHJlY3Qgd2lkdGg9IjIiIGhlaWdodD0iNzkiIHg9Ijc4Ii8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iMzkiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjU5Ii8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iMjAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSIyMCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjIwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iNDAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSI0MCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjQwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iNjAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSI2MCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjYwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSI3OSIgaGVpZ2h0PSIxIiB5PSIxOSIvPgogICAgICA8cmVjdCB3aWR0aD0iNzkiIGhlaWdodD0iMSIgeT0iMzkiLz4KICAgICAgPHJlY3Qgd2lkdGg9Ijc5IiBoZWlnaHQ9IjEiIHk9IjU5Ii8+CiAgICA8L2c+CiAgICA8cmVjdCB3aWR0aD0iODAiIGhlaWdodD0iMiIgeT0iNzgiIGZpbGw9IiNGRkYiLz4KICA8L2c+Cjwvc3ZnPgo=")
} */
```
