### ISSUE TITLE
Cannot preview normally in WYSIWYG mode

### ISSUE THREAD

**Issue by eryajf** [sissilab/obsidian-image-toolkit#60]
As the title

**Comment by sissilab** [comment]
> Cannot preview normally in WYSIWYG mode

What's WYSIWYG mode? Reading mode? Live Preview mode? Please provide more details.

**Comment by eryajf** [comment]
> What's WYSIWYG mode? Reading mode? Live Preview mode? Please provide more details.

Yes, it is Live preview mode

**Comment by sissilab** [comment]
> 

哥们，可以描述的再详细点吗？

**Comment by eryajf** [comment]
如图，我在实时预览模式下，无法放大浏览图片：
![May-11-2022 16-47-24](https://user-images.githubusercontent.com/33259379/167809289-28d87b19-35a6-40e5-b887-1f463640133f.gif)

**Comment by sissilab** [comment]
> 如图，我在实时预览模式下，无法放大浏览图片：

是鼠标点击图片时，图片消失了吗？松开鼠标，图片又回来了？
Reading 模式 是正常的吗？
怀疑跟你的主题有关，麻烦提供下主题名。

**Comment by eryajf** [comment]
> > 如图，我在实时预览模式下，无法放大浏览图片：
> 
> 是鼠标点击图片时，图片消失了吗？松开鼠标，图片又回来了？ Reading 模式 是正常的吗？ 怀疑跟你的主题有关，麻烦提供下主题名。

我用的这个主题：https://github.com/ZekunC/Obsidian-Typora-Vue-Theme

**Comment by eryajf** [comment]
好像是主题的原因，我切到官方默认镜像，这个问题消失了

**Comment by sissilab** [comment]
@eryajf 
编辑主题css文件，删除下面语句即可。
```css
.view-content img:not([class="emoji"]):active {
  cursor: zoom-out;    
  position: fixed;
  object-fit: contain;
  height: 100%;
  width: 100%;
  padding: 0;
  top: 50%;  
  left: 0;
  right: 0;
  bottom: 0;
  transform: translateY(-50%);
  z-index: 200;
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgdmlld0JveD0iMCAwIDgwIDgwIj4KICA8ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgPHJlY3Qgd2lkdGg9IjgwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjRjJGNEY2Ii8+CiAgICA8ZyBmaWxsPSIjRkZGIj4KICAgICAgPHJlY3Qgd2lkdGg9IjIiIGhlaWdodD0iNzkiIHg9Ijc4Ii8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iMzkiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjU5Ii8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iMjAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSIyMCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjIwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iNDAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSI0MCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjQwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjE5IiB4PSIxOSIgeT0iNjAiLz4KICAgICAgPHJlY3Qgd2lkdGg9IjEiIGhlaWdodD0iMTkiIHg9IjM5IiB5PSI2MCIvPgogICAgICA8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxOSIgeD0iNTkiIHk9IjYwIi8+CiAgICAgIDxyZWN0IHdpZHRoPSI3OSIgaGVpZ2h0PSIxIiB5PSIxOSIvPgogICAgICA8cmVjdCB3aWR0aD0iNzkiIGhlaWdodD0iMSIgeT0iMzkiLz4KICAgICAgPHJlY3Qgd2lkdGg9Ijc5IiBoZWlnaHQ9IjEiIHk9IjU5Ii8+CiAgICA8L2c+CiAgICA8cmVjdCB3aWR0aD0iODAiIGhlaWdodD0iMiIgeT0iNzgiIGZpbGw9IiNGRkYiLz4KICA8L2c+Cjwvc3ZnPgo=");
}
```
